# https://learn.microsoft.com/en-us/azure/logic-apps/set-up-model-context-protocol-server-standard

@logic_app_url = {{$dotenv logic_app_url}}

### 1. Initialize MCP Connection
# @name mcpConnection
POST {{logic_app_url}}/api/mcp
Content-Type: application/json
Accept: application/json, text/event-stream

{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "initialize",
  "params": {
    "protocolVersion": "2024-11-05",
    "capabilities": {},
    "clientInfo": {
      "name": "test-client",
      "version": "1.0.0"
    }
  }
}

### 2. List Available Tools
# @name mcpTools
POST {{logic_app_url}}/api/mcp
Content-Type: application/json
Mcp-Session-Id: {{mcpConnection.response.headers.Mcp-Session-Id}}
Accept: application/json, text/event-stream

{
  "jsonrpc": "2.0",
  "id": 2,
  "method": "tools/list",
  "params": {}
}


### 3. List tools of a specific MCP Logic App Server
# @name mcpLogicAppTools
POST {{logic_app_url}}/api/mcpservers/my-la-mcp-server1/mcp
Content-Type: application/json
Mcp-Session-Id: {{mcpConnection.response.headers.Mcp-Session-Id}}
Accept: application/json, text/event-stream

{
  "jsonrpc": "2.0",
  "id": 2,
  "method": "tools/list",
  "params": {}
}

### 4. Invoke a specific tool on a specific MCP Logic App Server
# @name mcpLogicAppResponse
POST {{logic_app_url}}/api/mcpservers/my-la-mcp-server1/mcp
Content-Type: application/json
Mcp-Session-Id: {{mcpConnection.response.headers.Mcp-Session-Id}}
Accept: application/json, text/event-stream

{
  "jsonrpc": "2.0",
  "id": 3,
  "method": "tools/call",
  "params": {
    "name": "stateful1",
    "arguments": {}
  }
}